print ("A founding member of the renowned Monty Python comedy troupe, Eric Idle")
print ("was born March 29, 1943, in South Shields, England; when he was just two years")
print ("old, his father, a member of the Royal Air Horse, died in an automobile crash.")
print ("After attending boarding school in Wolverhampton, Idle studied English at")
print ("Cambridge University, where he also served as president of the famed Footlights")
print ("comedy group in 1964. He first met future Python collaborators John Cleese and")
print ("Graham Chapman while appearing on the 1967 sketch comedy series At Last the 1948")
print ("Show, with the troupe -- also consisting of Michael Palin, Terry Jones, and")
print ("American-born animator Terry Gilliam -- beginning to truly take shape during")
print ("production of the children's program Do Not Adjust Your Set. In May of 1969, the")
print ("BBC contracted the group to produce their own 13-week program; Monty Python's Flying Circus, a weekly sketch comedy series, premiered that October, becoming a major hit throughout Europe and later a cult phenomenon overseas as well.") 
print ("In addition to their television series, Monty Python yielded a series of hit")
print ("films and albums; Idle, one of the group's chief writers, typically played")
print ("bizarre singers and other entertainer caricatures. In 1975, he published his")
print ("first novel, Hello Sailor, and with the Bonzo Dog Band's Neil Innes created")
print ("another sketch comedy series, the short-lived Rutland Weekend Television. The")
print ("show later gave rise to the Beatles parody group the Rutles, the subject of the")
print ("fan-favorite mockumentary All You Need Is Cash. Following the last official")
print ("Python project, the 1983 film Monty Python's the Meaning of Life, Idle accepted")
print ("small roles in a number of films, among them Gilliam's 1988 classic The")
print ("Adventures of Baron Munchausen, but otherwise focused on writing until")
print ("accepting the lead in 1990's Nuns on the Run. He also wrote, produced,")
print ("and starred in 1993's Splitting Heirs. In 1999, Idle inexplicably accepted a")
print ("supporting role on the misbegotten Brooke Shields sitcom Suddenly Susan; after")
print ("the show was abruptly canceled, the following year he mounted a solo tour in")
print ("support of his album Eric Idle Sings Monty Python.")
print ("~ Jason Ankeny")
